export type PracticeProblem = {
  id: string
  title: string
  body: string
  marks?: string
  tags?: string[]
}

export type PracticeSet = {
  id: string
  courseCode: string
  session: string
  setLabel?: string
  totalMarks?: string
  problems: PracticeProblem[]
}

export const practiceSets: PracticeSet[] = [
  {
    id: "ue21cs251a-esa-jan-may-2024",
    courseCode: "UE21CS251A - Digital Design and Computer Organization",
    session: "ESA Jan–May 2024",
    totalMarks: "100",
    problems: [
      {
        id: "1a",
        title: "SOP and POS simplification",
        marks: "8.0 Marks",
        body: "Simplify the given expressions to sum–of–products and product–of–sums form.",
        tags: ["Boolean Algebra", "Simplification", "SOP", "POS"],
      },
      {
        id: "1b",
        title: "Two-level NAND realization of simplified Boolean function",
        marks: "6.0 Marks",
        body: "Simplify the Boolean function and implement it with a two–level NAND gate circuit.",
        tags: ["NAND-NAND", "Simplification", "Implementation"],
      },
      {
        id: "1c",
        title: "Implement AND and XOR using a 2:1 multiplexer",
        marks: "6.0 Marks",
        body: "With the help of a 2:1 MUX, implement two–input AND and XOR gates.",
        tags: ["MUX", "Combinational", "Gate-Realization"],
      },
      {
        id: "2a",
        title: "Critical path and propagation delay",
        marks: "4.0 + 8.0 Marks",
        body: "Define critical path and propagation delay. Find the propagation delay of the given circuit where AND has 100 ps; NAND and XOR have 250 ps.",
        tags: ["Timing", "Delays"],
      },
      {
        id: "2b",
        title: "SR latch drawbacks and D-latch design",
        marks: "8.0 Marks",
        body: "List drawbacks of SR–latch, explain how they are handled. Provide schematic, truth table, and symbol of a D–latch.",
        tags: ["Latches", "Sequential"],
      },
      {
        id: "2c",
        title: "Divide-by-3 counter design",
        marks: "8.0 Marks",
        body: "Given the state transition diagram for a divide–by–3 counter, sketch the circuit using binary state encoding.",
        tags: ["Counters", "Sequential"],
      },
      {
        id: "3a",
        title: "Delay comparison: 32-bit Ripple-Carry vs Carry-Lookahead (4-bit blocks)",
        marks: "8.0 Marks",
        body: "Compare delays assuming 100 ps per 2-input gate and 300 ps per full adder.",
        tags: ["Adders", "Performance"],
      },
      {
        id: "3b",
        title: "16-bit prefix adder working principle",
        marks: "6.0 Marks",
        body: "Explain with a diagram the operation of a 16-bit prefix adder.",
        tags: ["Prefix Adder", "Combinational"],
      },
      {
        id: "3c",
        title: "Sequential circuit design with three flip-flops and given state diagram",
        marks: "8.0 Marks",
        body: "Design using D flip–flops treating unused states as don’t–care conditions.",
        tags: ["Sequential", "FSM", "D-FF"],
      },
      {
        id: "4a",
        title: "Non-restoring division algorithm",
        marks: "8.0 Marks",
        body: "Write the algorithm. Divide 1000 by 0011 using non-restoring method showing all steps.",
        tags: ["Arithmetic", "Division"],
      },
      {
        id: "4b",
        title: "IEEE 754 formats and decimal value conversion (single precision)",
        marks: "4.0 Marks",
        body: "Give IEEE single/double formats. Convert given numbers from single precision to decimal.",
        tags: ["IEEE 754", "Floating-Point"],
      },
      {
        id: "4c",
        title: "MIPS R-type instruction format",
        marks: "6.0 Marks",
        body: "Explain the R–type instruction format with an example.",
        tags: ["MIPS", "ISA"],
      },
      {
        id: "5a",
        title: "MIPS addressing modes",
        marks: "8.0 Marks",
        body: "List modes and identify the addressing modes for the given instructions.",
        tags: ["MIPS", "Addressing"],
      },
      {
        id: "5b",
        title: "Single-cycle control signals for R-type, lw, sw, addi",
        marks: "6.0 Marks",
        body: "Provide RegWrite, RegDst, AluSrc, and ALUOp control for each instruction.",
        tags: ["MIPS", "Control"],
      },
      {
        id: "5c",
        title: "Multi-cycle datapath schematic for sw instruction",
        marks: "6.0 Marks",
        body: "Give the schematic and describe control for multi-cycle sw.",
        tags: ["MIPS", "Datapath"],
      },
    ],
  },
  {
    id: "ue23cs251a-esa-dec-2024-set-2",
    courseCode: "UE23CS251A - Digital Design and Computer Organization",
    session: "ESA Dec 2024 (Set 2)",
    totalMarks: "100",
    problems: [
      {
        id: "1a",
        title: "Prime implicants and essential implicants",
        marks: "6.0 Marks",
        body: "Find all prime implicants for F(A,B,C,D)=Σ(0,2,3,5,7,8,10,11,14,15) and determine essential implicants.",
        tags: ["K-Map", "Prime Implicants"],
      },
      {
        id: "1b",
        title: "Gray-to-binary converter using XOR",
        marks: "8.0 Marks",
        body: "Design a combinational circuit that converts 4-bit Gray code to 4-bit binary using XOR gates.",
        tags: ["Code Conversion", "XOR"],
      },
      {
        id: "1c",
        title: "Three-output combinational circuit via NAND-decoder and NAND/AND",
        marks: "6.0 Marks",
        body: "Implement F1=Σ(1,4,6), F2=Σ(3,5), F3=Σ(2,4,6,7) using a decoder constructed with NANDs; minimize inputs of external gates.",
        tags: ["Decoder", "NAND Logic"],
      },
      {
        id: "1d",
        title: "Verilog for given circuit + testbench",
        marks: "5.0 Marks",
        body: "Write Verilog for the circuit shown and a testbench to verify.",
        tags: ["HDL", "Verification"],
      },
      {
        id: "2a",
        title: "PN flip-flop: tables, equations, conversion to D",
        marks: "8.0 Marks",
        body: "Characteristic table/equation, excitation table, and conversion PN→D.",
        tags: ["Flip-Flops", "Conversion"],
      },
      {
        id: "2b",
        title: "Four-bit universal shift register",
        marks: "6.0 Marks",
        body: "Define shift register; with diagram and function table explain 4-bit universal shift register.",
        tags: ["Shift Register"],
      },
      {
        id: "2c",
        title: "Design synchronous counter (sequence 0,4,2,1,6,0) using JK FFs",
        marks: "6.0 Marks",
        body: "Provide state assignment, excitation, and logic.",
        tags: ["Counters", "JK-FF"],
      },
      {
        id: "2d",
        title: "Verilog D-FF modules with and without reset",
        marks: "5.0 Marks",
        body: "Write two modules: D-FF, and D-FF with reset.",
        tags: ["HDL", "Flip-Flops"],
      },
      {
        id: "3a",
        title: "Micro-ops for ADD R1,R2,R3",
        marks: "6.0 Marks",
        body: "List register transfers and control commands assuming INSTR at address in PC.",
        tags: ["Micro-architecture", "Control"],
      },
      {
        id: "3b",
        title: "5-bit 2’s-complement subtraction and overflow",
        marks: "8.0 Marks",
        body: "Convert to 5-bit signed 2’s complement and subtract: (5,10),(7,13),(-14,11),(-3,-8). Identify overflow.",
        tags: ["2s-Complement", "Overflow"],
      },
      {
        id: "3c",
        title: "Effective address computation examples",
        marks: "5.0 Marks",
        body: "Given R1=1200, R2=4600, find effective addresses for: Load 20(R1), Move #3000, Store 30(R1,R2), Add –(R2), Sub (R1)+.",
        tags: ["Addressing", "Assembly"],
      },
      {
        id: "3d",
        title: "Multiple interrupts: daisy chaining vs priority arbitration",
        marks: "6.0 Marks",
        body: "Compare and contrast both mechanisms.",
        tags: ["Interrupts"],
      },
      {
        id: "4a",
        title: "Multiply (45×63) using Carry Save Addition",
        marks: "8.0 Marks",
        body: "Show partial products and intermediate sum/carry at each step.",
        tags: ["CSA", "Multiplication"],
      },
      {
        id: "4b",
        title: "IEEE-754 double for -58.25",
        marks: "6.0 Marks",
        body: "Binary conversion of |value|, normalize/exponent, bias, final double precision representation.",
        tags: ["IEEE 754", "Floating-Point"],
      },
      {
        id: "4c",
        title: "Control sequence for ADD (R3), R1 (single-bus datapath)",
        marks: "6.0 Marks",
        body: "Provide micro-steps for the indicated datapath.",
        tags: ["Datapath", "Control"],
      },
      {
        id: "4d",
        title: "Processor working principle with block diagram",
        marks: "5.0 Marks",
        body: "Illustrate entire processor operation with suitable diagram.",
        tags: ["CPU", "Architecture"],
      },
    ],
  },
  {
    id: "ue23cs251a-esa-dec-2024-set-1",
    courseCode: "UE23CS251A - Digital Design and Computer Organization",
    session: "ESA Dec 2024 (Set 1)",
    totalMarks: "100",
    problems: [
      {
        id: "1a",
        title: "Convert to sum of minterms and product of maxterms",
        marks: "4.0 + 5.0 Marks",
        body: "F(A,B,C,D)=B'D + A’D + BD. Express as Σm and ΠM.",
        tags: ["Minterms", "Maxterms"],
      },
      {
        id: "1b",
        title: "K-map simplification (4-variable)",
        marks: "8.0 Marks",
        body: "Simplify the given Boolean expression using four-variable maps.",
        tags: ["K-Map", "Simplification"],
      },
      {
        id: "1c",
        title: "Essential prime implicants based simplification",
        marks: "8.0 Marks",
        body: "Simplify by first finding essential prime implicants.",
        tags: ["Prime Implicants", "K-Map"],
      },
      {
        id: "1d",
        title: "BCD adder design",
        marks: "8.0 Marks",
        body: "Design a combinational BCD adder with input carry: truth table, correction condition, carry expression, and block diagram.",
        tags: ["BCD", "Adders"],
      },
      {
        id: "2a",
        title: "PN flip-flop tables and D conversion",
        marks: "8.0 Marks",
        body: "Characteristic table/equation, excitation table, and PN→D conversion.",
        tags: ["Flip-Flops"],
      },
      {
        id: "2b",
        title: "Sequential circuit with FA feeding D-FF; derive state table/diagram",
        marks: "6.0 + 7.0 Marks",
        body: "Given structure: derive state table and diagram.",
        tags: ["Sequential", "State Machine"],
      },
      {
        id: "2c",
        title: "Two D-FF sequential circuit with specified transitions",
        marks: "4.0 + 6.0 + 6.0 Marks",
        body: "Design with transitions: 00→11→01→10→00 if x_in=1, else hold.",
        tags: ["FSM", "D-FF"],
      },
      {
        id: "2d",
        title: "Ripple counter bit toggling",
        marks: "6.0 Marks",
        body: "How many FFs toggle next after counts: (a)1111000111 (b)0000001111.",
        tags: ["Counters", "Ripple"],
      },
      {
        id: "3a",
        title: "Processor-memory connections",
        marks: "8.0 Marks",
        body: "Explain with diagram how processor connects to memory.",
        tags: ["Architecture"],
      },
      {
        id: "3b",
        title: "Single-accumulator program for A×B + C×D",
        marks: "5.0 Marks",
        body: "Assume Load/Store/Multiply/Add; write a program.",
        tags: ["Assembly"],
      },
      {
        id: "3c",
        title: "Byte-addressable memory questions for word 42",
        marks: "8.0 + 5.0 + 6.0 Marks",
        body: "Find addresses; show 0xFF223344 layout in big/little endian.",
        tags: ["Memory", "Endianness"],
      },
      {
        id: "4a",
        title: "Booth multiplication (A=110101, B=011011)",
        marks: "8.0 Marks",
        body: "Perform signed Booth multiplication.",
        tags: ["Booth", "Multiplication"],
      },
      {
        id: "4b",
        title: "Nonrestoring integer division (Q=1000, M=00011)",
        marks: "6.0 Marks",
        body: "Perform the division with all steps.",
        tags: ["Division"],
      },
      {
        id: "4c",
        title: "Single-bus control steps for add immediate to R1",
        marks: "8.0 + 5.0 Marks",
        body: "Provide micro-steps for the datapath.",
        tags: ["Control", "Datapath"],
      },
      {
        id: "4d",
        title: "IEEE 754 single precision (42.3125) in hex",
        marks: "7.0 Marks",
        body: "Convert to IEEE-754 single precision and express in hex.",
        tags: ["IEEE 754"],
      },
    ],
  },
  {
    id: "ue22cs251a-esa-jan-may-2024",
    courseCode: "UE22CS251A - Digital Design and Computer Organization",
    session: "ESA Jan–May 2024",
    totalMarks: "100",
    problems: [
      {
        id: "1a",
        title: "Prime implicants and essential implicants for given expressions",
        marks: "8.0 Marks",
        body: "Find all prime implicants and identify essential ones.",
        tags: ["K-Map", "Prime Implicants"],
      },
      {
        id: "1b",
        title: "From circuit: Boolean formula, truth table, K-map minimization, number of prime implicants",
        marks: "5.0 + 5.0 + 8.0 + 7.0 Marks",
        body: "Analyze the given logic circuit and perform the listed tasks.",
        tags: ["Analysis", "K-Map"],
      },
      {
        id: "1c",
        title: "MUX implementation of F(A,B,C,D)=Σ(1,3,4,11,12,13,14,15)",
        marks: "5.0 Marks",
        body: "Show detailed logic using a multiplexer.",
        tags: ["MUX", "Implementation"],
      },
      {
        id: "1d",
        title: "i-verilog 4:1 MUX module (assume 2-input gates available)",
        marks: "8.0 Marks",
        body: "Write the module using available 2-input gates.",
        tags: ["HDL"],
      },
      {
        id: "2a",
        title: "Critical path and propagation delay; compute delay of given circuit",
        marks: "7.0 Marks",
        body: "AND=100 ps; NAND & XOR=250 ps.",
        tags: ["Timing"],
      },
      {
        id: "2b",
        title: "SR-latch drawbacks; D-latch schematic/truth table/symbol",
        marks: "5.0 Marks",
        body: "Explain and illustrate.",
        tags: ["Latches"],
      },
      {
        id: "2c",
        title: "Sequential circuit design with three FFs and given diagram",
        marks: "5.0 Marks",
        body: "Use D-FFs, treat unused states as don't care.",
        tags: ["FSM", "D-FF"],
      },
      {
        id: "2d",
        title: "i-verilog adder–subtractor (assume 2-input gates available)",
        marks: "5.0 Marks",
        body: "Write the module.",
        tags: ["HDL", "Arithmetic"],
      },
      {
        id: "3a",
        title: "32-bit RCA vs 32-bit CLA (4-bit blocks) delay comparison",
        marks: "8.0 Marks",
        body: "Assume 100 ps 2-input gate and 300 ps FA.",
        tags: ["Adders", "Performance"],
      },
      {
        id: "3b",
        title: "16-bit prefix adder working principle",
        marks: "8.0 Marks",
        body: "Explain with a diagram.",
        tags: ["Prefix Adder"],
      },
      {
        id: "3c",
        title: "IEEE 754 formats; convert given single-precision numbers to decimal",
        marks: "4.0 Marks",
        body: "Describe formats and convert.",
        tags: ["IEEE 754"],
      },
      {
        id: "3d",
        title: "Decode 32-bit instruction 0x02519804 (SLLV): identify fields",
        marks: "5.0 Marks",
        body: "Extract opcode, rs, rt, rd, shamt, funct.",
        tags: ["MIPS", "Decoding"],
      },
      {
        id: "4a",
        title: "MIPS ALU decoder truth table",
        marks: "7.0 Marks",
        body: "Provide ALU control mapping.",
        tags: ["Control"],
      },
      {
        id: "4b",
        title: "Multi-cycle execution of R-type instructions",
        marks: "8.0 Marks",
        body: "Explain control signals across cycles.",
        tags: ["Datapath", "Control"],
      },
      {
        id: "4c",
        title: "Fetch-phase control signals in MIPS multi-cycle",
        marks: "5.0 Marks",
        body: "List IorD, AluSrcA, AluSrcB, ALUOp, PCSrc.",
        tags: ["Control"],
      },
      {
        id: "4d",
        title: "MIPS addressing modes",
        marks: "5.0 Marks",
        body: "Discuss available addressing modes.",
        tags: ["Addressing"],
      },
    ],
  },
]
